# Generated by Django 4.2.3 on 2023-08-22 00:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_order_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
